tork/urls.py
#! /usr/bin/python
# -*- encoding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin
from views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', pagina_inicio,name='inicio'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('apps.main.urls')),
    url(r'^registro/$', registro, name='registro'),
    url(r'^edit_profile/$', edit_profile, name='edit_profile'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^login/$', login, name='login'),
	
)

apps/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals
# Create your models here.

class TipoDoc(models.Model):
	descripcion 	= models.CharField(max_length=10,unique=True)

	def __unicode__(self):
		return u"%s" % self.descripcion
	
	class Meta:
		db_table = 'tipo_documento'


class UserProfile(models.Model):
	user 		= models.OneToOneField(User)
	tipo_doc	= models.ForeignKey('TipoDoc',null=True,blank=True,on_delete=models.PROTECT)
	nro_doc		= models.IntegerField(null=True,blank=True)
	localidad	= models.CharField(max_length=100,null=True,blank=True)
	calle		= models.CharField(max_length=100,null=True,blank=True)
	apto		= models.BooleanField(default=True)
	anulado		= models.BooleanField(default=False)

	class Meta:
		db_table = 'UserProfile'
		unique_together= ('tipo_doc','nro_doc',)

	def user_profile(sender, instance, signal,*args,**kwargs):
		profile, new = UserProfile.objects.get_or_create(user=instance)

	signals.post_save.connect(user_profile,sender=User)

class Provincia(models.Model):
	nombre		= models.CharField(max_length=50)

	class Meta:
		db_table	= 'provincia'

class Localidad(models.Model):
	nombre		= models.CharField(max_length=50)
	provincia 	= models.ForeignKey('Provincia',on_delete=models.PROTECT)

	class Meta:
		db_table='localidad'	

class EstadoPedido(models.Model):
	descripcion	= models.CharField(max_length=50)

	class Meta:
		db_table = 'estado_pedido'

class Categoria(models.Model):
	descripcion	= models.CharField(max_length=100)

	def __unicode__(self):
		return u"%s" % self.descripcion

	def puedo_eliminar():

		return User.objects.get(username=request.user).is_staff()

	class Meta:
		db_table = 'categoria'

class Producto(models.Model):
	categoria 		= models.ForeignKey('Categoria',on_delete=models.PROTECT)
	nombre			= models.CharField(max_length=100)
	marca			= models.CharField(max_length=100)
	espec			= models.TextField(max_length=250,null=True,blank=True)
	stock_minimo	= models.IntegerField()
	punto_reorden	= models.IntegerField()
	stock_maximo	= models.IntegerField()
	stock_actual	= models.IntegerField()
	imagen			= models.ImageField(upload_to='productos/', null=True, blank=True)
	costo			= models.DecimalField(max_digits=7, decimal_places=2)

	def puedo_eliminar():

		return User.objects.get(username=request.user).is_staff()

	def __unicode__(self):
		return u"%s - %s" % (self.nombre,self.marca)

	class Meta:
		db_table	= 'producto'


class TipoEnvio(models.Model):
	descripcion 	= models.CharField(max_length=40)

	def __unicode__(self):
		return u'%s' % self.descripcion

	class Meta:
		db_table 	= 'tipo_envio'

class MetodoPago(models.Model):
	descripcion 	= models.CharField(max_length=40)

	def __unicode__(self):
		return u'%s' % self.descripcion

	class Meta:
		db_table 	= 'metodo_pago'

class Pedido(models.Model):
	fecha_carga		= models.DateField(auto_now=True)
	cliente 		= models.ForeignKey('UserProfile',on_delete=models.PROTECT)
	estado_pedido	= models.ForeignKey('EstadoPedido',on_delete=models.PROTECT)
	tipo_envio		= models.ForeignKey('TipoEnvio', on_delete=models.PROTECT,null=True,blank=True)
	metodo_pago		= models.ForeignKey('MetodoPago', on_delete=models.PROTECT,null=True,blank=True)
	observaciones	= models.CharField(max_length=100,blank=True,null=True)

	class Meta:
		db_table	= 'pedido'

class ProductoPedido(models.Model):
	pedido 		= models.ForeignKey('Pedido',on_delete=models.PROTECT)
	producto 	= models.ForeignKey('Producto',on_delete=models.PROTECT)
	cantidad	= models.IntegerField(null=True,blank=True)
	anulado		= models.BooleanField(default=False)
	costo		= models.DecimalField(max_digits=7, decimal_places=2,null=True,blank=True)
	observaciones	= models.CharField(max_length=100,blank=True,null=True)


	class Meta:
		db_table	= 'producto_pedido'

class TipoFactura(models.Model):
	descripcion 	= models.CharField(max_length=100)

	def __unicode__(self):
		return u'%s' % self.descripcion
	
	class Meta:
		db_table	= 'tipo_factura'



class Factura(models.Model):
	cliente	= models.ForeignKey('UserProfile',on_delete=models.PROTECT)
	tipo 	= models.ForeignKey('TipoFactura',on_delete=models.PROTECT,null=True,blank=True)
	pedido 	= models.OneToOneField('Pedido',on_delete=models.PROTECT,related_name='factura_pedido')
	fecha 	= models.DateField(auto_now=True)
	total	= models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)
	pagado	= models.BooleanField(default=False)
	fecha_pago	= models.DateField(null=True,blank=True)

	class Meta:
		db_table =	'factura'
		unique_together = ('cliente','pedido',)

class DetalleFactura(models.Model):
	factura 		= models.ForeignKey('Factura',on_delete=models.PROTECT,related_name="detalle")
	pedido_producto	= models.ForeignKey('ProductoPedido',on_delete=models.PROTECT)
	costo			= models.DecimalField(max_digits=10,decimal_places=2)

	class Meta:
		db_table 	= 'detalle_factura'

class Oferta(models.Model):
	producto 		= models.ForeignKey('Producto',on_delete=models.PROTECT)
	fecha_inicio	= models.DateField()
	fecha_fin		= models.DateField()
	costo			= models.DecimalField(max_digits=7,decimal_places=2)

	def puedo_eliminar():

		return User.objects.get(username=request.user).is_staff()

	class Meta:
		db_table = 'Oferta'

apps/main/forms.py
#! /usr/bin/python
# -*- encoding: utf-8 -*-

from django import forms 
from apps.main.models import *


attrs_dict = { 'class': 'required' }

class LoginForm(forms.Form):
	usuario = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required span9','placeholder':'Usuario'})))
	password = forms.CharField(widget=forms.PasswordInput(attrs=dict({'class':'required span9','placeholder':'Contraseña'}), render_value=False))



class RegistracionForm(forms.Form):
    
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=75)), label=(u'Dirección de email'))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),label=(u'Clave'))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),label=(u'Clave (de nuevo)'))
    nombre	  = forms.CharField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=75)), label=(u'Nombre'))
    apellido  = forms.CharField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=75)), label=(u'Apellido'))	
    tipo_documento = forms.ModelChoiceField(widget=forms.Select(attrs=dict(attrs_dict)), queryset= TipoDoc.objects.all(),label=(u'Tipo de documento'))
    numero_documento = forms.IntegerField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=10)), label=(u'Numero Documento'))
    localidad        = forms.CharField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=100)), label=(u'Ciudad')) 
    calle        = forms.CharField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=100)), label=(u'Calle')) 

    def clean_username(self):
        
        """
        Valida si el username ya existe en la base de datos
        """
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['email'])
        except User.DoesNotExist:
            return self.cleaned_data['email']
        raise forms.ValidationError(_(u'Este email ya esta registrado en nuestra base de datos.'))
    
    
    def clean(self):
        """
        Verificamos si password1 y password2 son iguales
        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError((u'Tienes que ingresar la misma clave en los dos campos'))
        return self.cleaned_data
    
        
    def save(self, profile_callback=None):
        """
        Creamos el usuario, el cliente y relacionamos el cliente con el usuario
        """
        
        username = self.cleaned_data['email']
        password = self.cleaned_data['password1']
        email    = self.cleaned_data['email']
        
        usuario = User.objects.create_user(username, email, password)
        usuario.is_active = True
        usuario.first_name = self.cleaned_data['nombre']
        usuario.last_name = self.cleaned_data['apellido']
        usuario.save()
        
        return usuario

class UserProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		exclude = ('user','apto','anulado')

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria

class ProductoForm(forms.ModelForm):

    class Meta:
        model=Producto

class OfertaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(widget=forms.Select(), queryset= Categoria.objects.all(),label=(u'Categoria'))
    fecha_inicio = forms.DateField(widget=forms.DateInput())
    class Meta:
        model = Oferta

class PedidoForm(forms.ModelForm):

    class Meta:
        model = Pedido
        exclude = ('fecha_carga','cliente','estado_pedido','observaciones')

class ProductoPedidoForm(forms.Form):
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs=dict(attrs_dict)))

class FacturaForm(forms.ModelForm):


    class Meta:
        model = Factura
        exclude = ('cliente','pedido','total','pagado','fecha_pago')

templates/intranet/categorias.html
{% extends "base.html" %}
{% block breadcrumb %}
	<li><a href="{% url 'categorias' %}">Categorias</a> <span class="divider">/</span></li>
{% endblock %}
{% block cuerpo %}
	<h1> Alta y baja de Categorias </h1>
	<hr>
	<form method="POST" action="{% url 'categorias' %}">
		
		<ul class="nav navbar">
			{% csrf_token %}
			{{categoria.as_ul}}
			<li>
				<input type="submit" class="btn btn-small btn-success" value="Grabar"/>
			</li>
		</ul>
	</form>
	<h3>Listado de categorias</h3>
	<table class="table table-condensed table-bordered table-hover" id="table" name="table">
  		<thead>
  			<tr>
  				<th>
  				</th>
	  			<th>
	  				Descripcion	
	  			</th>
	  			<th>
	  			</th>
	  			<th>
	  			</th>
  			</tr>
  		</thead>
  		<tbody>
  		{% for cat in categorias %}
			<tr>
				<td>{{cat.id}}</td>
				<td>{{cat.descripcion}}</td>
				<td><a href="{% url 'edit_categorias' cat.id %}"><i class="icon-edit"></i></a></td>
				<td><a href="{% url 'borrar_categoria' cat.id %}"><i class="icon-trash"></i></a></td>
			</tr>
		{% endfor %}	
		</tbody>
	</table>


	
{% endblock %}

templates/intranet/edit_categorias.html
{% extends "base.html" %}
{% block breadcrumb %}
	<li><a href="{% url 'categorias' %}">Categorias</a> <span class="divider">/</span></li>
	<li><a href="{% url 'edit_categorias' cat.id %}">{{cat}}</a> <span class="divider">/</span></li>
{% endblock %}
{% block cuerpo %}
	<h1> Alta y baja de Categorias </h1>
	<hr>
	<form method="POST" action="{% url 'edit_categorias' cat.id %}">
		
		<ul class="nav navbar">
			{% csrf_token %}
			{{categoria.as_ul}}
			<li>
				<input type="submit" class="btn btn-small btn-success" value="Grabar"/>
			</li>
		</ul>
	</form>
	<h3>Listado de categorias</h3>
	<table class="table table-condensed table-bordered table-hover" id="table" name="table">
  		<thead>
  			<tr>
  				<th>
  				</th>
	  			<th>
	  				Descripcion	
	  			</th>
	  			<th>
	  			</th>
	  			<th>
	  			</th>
	  		</tr>
  		</thead>
  		{% for cat in categorias %}
  		<tbody>
		<tr>
			<td>{{cat.id}}</td>
			<td>{{cat.descripcion}}</td>
			<td><a href="{% url 'edit_categorias' cat.id %}"><i class="icon-edit"></i></a></td>
			<td><a href="{% url 'borrar_categoria' cat.id %}"><i class="icon-trash"></i></a></td>
		</tr>
		</tbody>
		{% endfor %}	
	</table>


	
{% endblock %}

templates/intranet/edit_ofertas.html
{% extends 'base.html' %}
{% block breadcrumb %}
	<li><a href="{% url 'ofertas' %}">Ofertas</a> <span class="divider">/</span></li>
	<li><a href="{% url 'edit_ofertas' of.id %}">{{of.producto}}</a> <span class="divider">/</span></li>
{% endblock %}
{% block cuerpo %}
	<h1> Alta y baja de Ofertas </h1>
	<hr>
	<div class="row">
		<div class="span5 offset1">
			<form method="POST" action="{% url 'edit_ofertas' of.id %}">{% csrf_token %}
				<p><label for="id_categoria">Categoria:</label> 
					<select id="id_categoria" name="categoria">
						<option value={{oferta.categoria}}</option>
					</select>
				</p>
				<p><label for="id_producto">Producto:</label> 
					<select id="id_producto" name="producto">
							<option {{oferta.producto}}</option>
					</select>
				</p>
				<p><label for="id_fecha_inicio">Fecha inicio:</label> 
					{{ oferta.fecha_inicio }} 
				</p>
				<p><label for="id_fecha_fin">Fecha fin:</label> 
					{{ oferta.fecha_fin }}
				</p>
				<p><label for="id_costo">Costo:</label> 
					{{oferta.costo}}
				</p>
				<p>
					<input type="submit" class="btn btn-small btn-success" value="Grabar" />
				</p>
			</form>
		</div>
		<div class="span3">
			<img src="{{STATIC_URL}}{{of.producto.imagen}}"/>
		</div>
	</div>
	<h3>Listado de ofertas</h3>
			<table class="table table-condensed table-bordered table-hover" id="table" name="table">
		  		<thead>
		  				<th>
		  					
		  				</th>
			  			<th>
			  				Categoria
			  			</th>
			  			<th>
			  				Descripcion	
			  			</th>
			  			<th>
			  				Costo
			  			</th>
			  			<th>
			  				Desde
			  			</td>
			  			<th>
			  				Hasta
			  			</th>
			  			<th>
			  			</th>
			  			<th>
			  			</th>
			  		
		  		</thead>

		  		{% for oferta in ofertas %}
		  		<tbody>
				<tr>
					<td>{{oferta.id}}</td>
					<td>{{oferta.producto.categoria}}</td>
					<td>{{oferta.producto.descripcion}}</td>
					<td>${{oferta.costo}}</td>
					<td>{{oferta.fecha_inicio}}</td>
					<td>{{oferta.fecha_fin}}</td>
					<td><center><a href="{% url 'edit_ofertas' oferta.id %}"><i class="icon-edit"></i></a></center></td>
					<td><center><a href="{% url 'borrar_oferta' oferta.id %}"><i class="icon-remove-sign"></i></a></center></td>
				</tr>
				</tbody>
				{% endfor %}	
			</table>

{% endblock %}

templates/intranet/edit_productos.html
{% extends "base.html" %}
{% block breadcrumb %}
	<li><a href="{% url 'productos' %}">Productos</a> <span class="divider">/</span></li>
	<li><a href="{% url 'edit_productos' prod.id %}">{{prod}}</a> <span class="divider">/</span></li>
{% endblock %}
{% block cuerpo %}
	<h1> Alta y baja de Productos </h1>
	<hr>
	<div class="row">
		<div class="span3 offset1">
			<form method="POST" action="{% url 'edit_productos' prod.id %}" enctype="multipart/form-data">
				
				<ul class="nav navbar">
					{% csrf_token %}
					{{producto.as_ul}}
					
						
					
				</ul>
				<button type="submit" class="btn btn-small btn-success">Grabar</button>
			</form>
			  <a href="{% url 'productos' %}" title="first tooltip"><i class="icon-refresh"></i> </a>
		</div>
		<div class="span3">
			<img src="{{STATIC_URL}}{{prod.imagen}}"/>
		</div>
	</div>
	<h3>Listado de productos</h3>
			<table class="table table-condensed table-bordered table-hover" id="table" name="table">
		  		<thead>
			  		<tr>
			  			<th>
			  				
			  			</th>
			  			<th>
			  				Categoria
			  			</th>
			  			<th>
			  				Descripcion	
			  			</th>
			  			<th>
			  				Marca
			  			</th>
			  			<th>
			  			</th>
			  			<th>
			  			</th>
			  		</tr>
		  		</thead>
		  		{% for prod in productos %}
		  		<tbody>
				<tr>
					<td>{{prod.id}}</td>
					<td>{{prod.categoria}}</td>
					<td>{{prod.nombre}}</td>
					<td>{{prod.marca}}</td>
					<td><center><a href="{% url 'edit_productos' prod.id %}"><i class="icon-edit"></i></a></center></td>
					<td><center><a href="{% url 'borrar_producto' prod.id %}"><i class="icon-remove-sign"></i></a></center></td>
				</tr>
				</tbody>
				{% endfor %}	
			</table>
{% endblock %}

templates/intranet/factura.html
{% extends "base.html" %}
{% block cuerpo %}

<form method="post" action="{% url 'facturar_pedido' factura.pedido.id %}"> {%csrf_token%} 
<div class="container">
	<div class="row">
		<div class="span8 offset1">
			<div class="row">
				<div class="span4">
					<img src="{{STATIC_URL}}img/logo.png" />
				</div>
				<div class="span4">
					
						<strong>Fecha: </strong> {{factura.fecha}}
						{{form}}
					
				</div>
				<div class="span4">
					<p>
						<strong>Cliente: </strong> {{factura.cliente.user.first_name}} {{factura.cliente.user.last_name}}
					</p>
					<p>
						<strong>Domicilio: </strong> {{factura.cliente.calle}} - {{factura.cliente.localidad}}
					</p>
				</div>
			</div>
			<div class="row">
				<div class="span12">
					<table class="table">
						<thead>
							<tr>
								<th>
									Producto
								</th>
								<th>
									Cantidad
								</th>
								<th>
									Precio Unitario
								</th>
								<th>
									Total
								</th>
							</tr>
						</thead>
						<tbody>
							{% for renglon in detalle %}	
							<tr>
								<td>
									{{renglon.pedido_producto.producto}}
								</td>
								<td>
									{{renglon.pedido_producto.cantidad}}
								</td>
								<td>
									{{renglon.pedido_producto.costo}}
								</td>
								<td>
									{{renglon.costo}}
								</td>
							</tr>
							{% endfor %}
						</tbody>
						<tfoot>
							<tr>
								<td colspan="3">
									Total
								</td>
								<td>
									${{factura.total}}
								</td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
	<button type="submit" class="btn-success btn-mini"> Guardar Factura </button>
</div>
<form>
{% endblock %}

templates/intranet/gestion_pedidos.html
{% extends "base.html" %}

{% block cuerpo %}
<div class="container">
	<div class="row">
		<div class="span8 offset1">
			<h3 class="text-info text-right">
				Gestion de Pedidos
			</h3>
			<table class="table table-striped table-hover table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							N° Pedido
						</th>
						<th>
							Cliente
						</th>
						<th>
							Fecha
						</th>
						<th>
							Forma de pago
						</th>
						<th>
							Metodo de envio
						</th>
						<th>
							Estado
						</th>
						<th>
						</th>
					</tr>
				</thead>
				<tbody>
					{% for pedido in pedidos %}
					<tr>
						<td>
							{{pedido.id}}
						</td>
						<td>
							{{pedido.cliente.user.first_name}} {{pedido.cliente.user.last_name}}
						</td>
						<td>
							{{pedido.fecha_carga}}
						</td>
						<td>
							{{pedido.metodo_pago}}
						</td>
						<td>
							{{pedido.tipo_envio}}
						</td>
						<td>
							{% if pedido.estado_pedido.descripcion == 'Confirmado' %}
								<span class="label label-important">{{pedido.estado_pedido.descripcion}}</span>
							{% elif pedido.estado_pedido.descripcion == 'Procesado' or pedido.estado_pedido.descripcion == 'Facturado' %}
								<span class="label label-success">{{pedido.estado_pedido.descripcion}}</span>
							{% elif pedido.estado_pedido.descripcion == 'Enviado' %}
								<span class="label label-info">{{pedido.estado_pedido.descripcion}}</span>
							{% elif pedido.estado_pedido.descripcion == 'Rechazado' %}
								<span class="label label-default">{{pedido.estado_pedido.descripcion}}</span>
							{% endif %}
						</td>
						<td>
							{% if pedido.estado_pedido.descripcion == 'Confirmado' %}
								<a href="{% url 'procesa_pedido' pedido.id %}"><i class="icon-pencil"></i></a>
							{% elif pedido.estado_pedido.descripcion == 'Procesado' %}
								<a href="{% url 'facturar_pedido' pedido.id %}"><i class="icon-file" title="Cerrar Factura"></i></a>
							{% elif pedido.estado_pedido.descripcion == 'Facturado' %}
								<a href="{% url 'despachar_pedido' pedido.id %}"><i class="icon-envelope" title="Despachar Pedido"></i></a>
							{% elif pedido.estado_pedido.descripcion == 'Enviado' %}
								<a href="{% url 'registrar_pago' pedido.id %}"><i class="icon-ok" title="Registrar Pago"></i></a>
							{% elif pedido.estado_pedido.descripcion == 'Rechazado' %}
								<i class="icon-remove"></i>
							{% endif %}
						</td>
					</tr>
					{% endfor %}	
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}

templates/intranet/ofertas.html
{% extends 'base.html' %}
{% block breadcrumb %}
	<li><a href="{% url 'ofertas' %}">Ofertas</a> <span class="divider">/</span></li>
{% endblock %}
{% block cuerpo %}
	<h1> Alta y baja de Ofertas </h1>
	<hr>
	<form method="POST" action="{% url 'ofertas' %}">{% csrf_token %}
		<p><label for="id_categoria">Categoria:</label> 
			<select id="id_categoria" name="categoria">
				<option value={{oferta.categoria}}</option>
			</select>
		</p>
		<p><label for="id_producto">Producto:</label> 
			<select id="id_producto" name="producto">
					<option value="0"></option>
			</select>
		</p>
		<p><label for="id_fecha_inicio">Fecha inicio:</label> 
			<input id="id_fecha_inicio" name="fecha_inicio" type="date" />
		</p>
		<p><label for="id_fecha_fin">Fecha fin:</label> 
			<input id="id_fecha_fin" name="fecha_fin" type="date" />
		</p>
		<p><label for="id_costo">Costo:</label> 
			<input id="id_costo" name="costo" type="text" />
		</p>
		<p>
			<input type="submit" class="btn btn-small btn-success" value="Grabar"/>	
		</p>
	</form>
	
	<h3>Listado de ofertas</h3>
			<table class="table table-condensed table-bordered table-hover" id="table" name="table">
		  		<thead>
			  		<tr>
			  			<th>
			  				
			  			</th>
			  			<th>
			  				Categoria
			  			</th>
			  			<th>
			  				Descripcion	
			  			</th>
			  			<th>
			  				Costo
			  			</th>
			  			<th>
			  				Desde
			  			</th>
			  			<th>
			  				Hasta
			  			</th>
			  			<th>
			  			</th>
			  			<th>
			  			</th>
			  		</tr>
		  		</thead>
		  		{% for oferta in ofertas %}
		  		<tbody>
				<tr>
					<td>{{oferta.id}}</td>
					<td>{{oferta.producto.categoria}}</td>
					<td>{{oferta.producto.descripcion}}</td>
					<td>${{oferta.costo}}</td>
					<td>{{oferta.fecha_inicio}}</td>
					<td>{{oferta.fecha_fin}}</td>
					<td><center><a href="{% url 'edit_ofertas' oferta.id %}"><i class="icon-edit"></i></a></center></td>
					<td><center><a href="{% url 'borrar_oferta' oferta.id %}"><i class="icon-remove-sign"></i></a></center></td>
				</tr>
				</tbody>
				{% endfor %}	
			</table>

{% endblock %}

templates/intranet/productos.html
{% extends "base.html" %}
{% block breadcrumb %}
	<li><a href="{% url 'productos' %}">Productos</a> <span class="divider">/</span></li>
{% endblock %}
{% block cuerpo %}
	<h1> Alta y baja de Productos </h1>
	<hr>
	<form method="POST" action="{% url 'productos' %}" enctype="multipart/form-data">
		
		<ul class="nav navbar">
			{% csrf_token %}
			{{producto.as_ul}}
			<li>
				<input type="submit" class="btn btn-small btn-success" value="Grabar"/>
			</li>
		</ul>
	</form>
	<h3>Listado de productos</h3>
			<table class="table table-condensed table-bordered table-hover" id="table" name="table">
		  		<thead>
			  		<tr>
			  			<th>
			  				
			  			</th>
			  			<th>
			  				Categoria
			  			</th>
			  			<th>
			  				Descripcion	
			  			</th>
			  			<th>
			  				Marca
			  			</th>
			  			<th>
			  				Stock
			  			</th>
			  			<th>
			  				Costo
			  			</th>
			  			<th>
			  			</th>
			  			<th>
			  			</th>
			  		</tr>
		  		</thead>
		  		{% for prod in productos %}
		  		<tbody>
				<tr>
					<td>{{prod.id}}</td>
					<td>{{prod.categoria}}</td>
					<td>{{prod.nombre}}</td>
					<td>{{prod.marca}}</td>
					<td>
		  				{{prod.stock_actual}}
		  			</td>
		  			<td>
		  				{{prod.costo}}
		  			</td>
		  			<td><center><a href="{% url 'edit_productos' prod.id %}"><i class="icon-edit"></i></a></center></td>
					<td><center><a href="{% url 'borrar_producto' prod.id %}"><i class="icon-remove-sign"></i></a></center></td>
				</tr>
				</tbody>
				{% endfor %}	
			</table>


	
{% endblock %}